leikoilja/glocaltokens

- glocaltokens/client.py
- setup.py
Im not a professional programmer but i think this solves the problem with jq
> Removal of jq dependancy

- README.md
If you try to get a master token to often, google will disconnect your other android devices.
> Update explanation to make sure that others use your script corretly

- .pre-commit-config.yaml
- glocaltokens/client.py
Adding better logging and pre-commit hooks that mandate all the code to be Black
Closes https://github.com/leikoilja/glocaltokens/issues/16
> Adding logging and pre-commit hooks

- glocaltokens/client.py
> Fix authentication (401) error in `get_homegraph`

- .github/workflows/build.yml
- .github/workflows/glocaltokens_ci.yml
- setup.py
Adding github workflows for CI for glocaltokens
> Adding CI using Github workflows

- .github/workflows/linting-and-testing.yaml
- .pre-commit-config.yaml
- MANIFEST.in
- example/get_tokens.py
- glocaltokens/client.py
- glocaltokens/scanner.py
- mypy.ini
- setup.cfg
- tests/assertions.py
- tests/factory/providers.py
- tests/test_client.py
The beginning of setting up mypy
- sets up pre commit hooks for mypy
- sets up CI job for mypy
Closes #43
> Setting up mypy

- glocaltokens/client.py
- glocaltokens/scanner.py
- tests/test_client.py
- tests/test_scanner.py
> Propagate logging level to scanner and add remove_service method

- .github/dependabot.yml
- .github/labeler.yml
- .github/labels.yml
- .github/release-drafter.yml
- .github/workflows/build.yml
- .github/workflows/labeler.yml
- .github/workflows/manage-labels.yml
- CONTRIBUTING.md
- Setup Dependabot
- Setup Labeler
- Update release drafter template
- Update list of valid labels
- Update labeler rules
- Fix mistakes in CONTRIBUTING.md
> Backport changes from ha-google-home

- glocaltokens/client.py
- poetry.lock
- pyproject.toml
- setup.cfg
It was recently updated to 1.0.0 and this includes few important changes:
- List of used ciphers is now hardcoded, this should make authorisation more reliable.
- It's strictly typed and exports typing information. This highlighted few bugs when username and password were not checked.
> Update gpsoauth to 1.0.0

- .pre-commit-config.yaml
- example/get_tokens.py
- glocaltokens/client.py
- glocaltokens/const.py
- glocaltokens/scanner.py
- glocaltokens/utils/logs.py
- glocaltokens/utils/network.py
- glocaltokens/utils/token.py
- glocaltokens/utils/types.py
- pyproject.toml
- tests/assertions.py
- tests/factory/providers.py
- tests/test_client.py
- tests/test_scanner.py
- tests/test_utils.py
Enabling pylint and linting
Breaking change: changing `device.ip` to `device.ip_address`
> Enabling pylint

- glocaltokens/client.py
- tests/assertions.py
- tests/test_client.py
The current logging format is a bit messy. It's hard to follow and still prints tokens at some places
Example:
> 2021-04-03 16:12:26 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2021-04-03 16:12:26 DEBUG (MainThread) [glocaltokens.client] Set self username to "u*************************", password to "2*************", master_token to "a******************************************************************************************************************************************************************************************************************************" and android_id to 1*************
2021-04-03 16:12:26 DEBUG (MainThread) [glocaltokens.client] Set self access_token, homegraph, access_token_date and homegraph_date to None
2021-04-03 …
> Improving logging

- pyproject.toml
Getting ready for https://github.com/leikoilja/glocaltokens/releases/tag/v0.3.0
> Bumping up the version

- glocaltokens/client.py
While working on a PR for [leikoilja/ha-google-home](https://github.com/leikoilja/ha-google-home) I've noticed a typo :)
> Fix typo in 'successfully'

- .github/dependabot.yml
Reverts leikoilja/glocaltokens#79
It actually prevents from adding language label 🙁
> Revert "Cleanup depdendabot config"

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/build.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- glocaltokens/client.py
- glocaltokens/utils/logs.py
- poetry.lock
- pyproject.toml
- setup.cfg
- tests/test_scanner.py
Codespell can find typos without being annoying.
Also I noticed that prettier was missing. Add some [order](https://www.youtube.com/watch?v=yHE1uM_NF4Y).
> Setup codespell

- glocaltokens/client.py
- glocaltokens/const.py
- tests/test_client.py
Generate 12 random chars.
Closes #65
> Fix MAC address generation

- .github/workflows/build.yml
- README.md
Adds total download badge to the readme as this:
Also renames github action and removes styles from badges
> Adding downloads badge to the README

- glocaltokens/client.py
- glocaltokens/types.py
- poetry.lock
- tests/assertions.py
- tests/factory/providers.py
- tests/test_client.py
Discovered that foyer API that we call already contains `device_info` with `device_id` that we can grab and use... How cool? 
Closes #75
> Grabbing unique device id from foyer API

- glocaltokens/client.py
- setup.cfg
- tests/test_client.py
This probably doesn't happen but better safe than sorry.
Retry for 3 times.
> Fix potential infinite loop in get_homegraph

- CONTRIBUTING.md
- glocaltokens/google/internal/home/foyer/v1.proto
- glocaltokens/google/internal/home/foyer/v1_pb2.py
Cleanup `None` message, it was replaced with `GetAssistantRoutinesRequest`. You can't have name `None` in python, it's reserved for constant.
Move high level comment to the top, otherwise it's merged with the next comment by `protoc`.
> Small cleanup in proto file

- .kodiak.toml
Add config to auto-merge Dependabot PRs.
> Add Kodiak github app

- glocaltokens/client.py
- tests/test_client.py
> Added `ValueError` handler for long passwords

- .github/workflows/build.yml
- .github/workflows/linting-and-testing.yaml
- .github/workflows/publish.yml
New version supports new lock file format.
> Bump poetry to 1.3.2

- .github/workflows/release-drafter.yml
- It should only run on pushes on master
- Add names
- Cleanup comments
> Disable release-drafter job on PRs

- poetry.lock
Update `ipython` and `certifi` to the latest versions.
These are found by Github on Security tab.
> Fix potential security vulnerabilities

- poetry.lock
- pyproject.toml
> Require gpsoauth^1.1.1

- .github/workflows/build.yml
- .github/workflows/linting-and-testing.yaml
- .github/workflows/publish.yml
- .pre-commit-config.yaml
- pyproject.toml
Cache installed dependencies with Poetry and Pre-Commit hooks to make CI much faster.
I setup it in my other repos and it work really well.
> Enable caches on CI

- .pre-commit-config.yaml
There are few toml files in the repo, main one is `pyproject.toml`. Add this small hook to ensure toml syntax is correct.
> Add check-toml pre-commit hook
