leikoilja/glocaltokens

README.md
glocaltokens/client.py

Now, when an access token is generated, the generation date will be stored, and since its duration is of one hour, once that time is over, a new one will be generated. A bit of code reformatting has been done.
Also, some "security recommendations" have been added to the README.

Added access token expiration

---

.github/workflows/tests.yaml
tox.ini

Adding support for python 3.9 to tox.ini and setting up github action.
Closes #26

Adding support for python 3.9

---

.pre-commit-config.yaml
glocaltokens/client.py
glocaltokens/const.py
requirements
tests/test_client.py

The method which generates random android id relies on from uuid import getnode that is underlying the hardware address. On amd devices this method return 14 digits number, while on arm 15 digits long number.
Closes #21

Improve Android ID generation

---

glocaltokens/client.py
tests/factory/providers.py
tests/test_client.py
tests/test_scanner.py

Haven't really had time to finish it up with `homegraph` and `get_devices`, but added some client tests to make sure we fetch tokens right.

Adding client tests for fetching tokens

---

glocaltokens/client.py
glocaltokens/const.py
tests/test_client.py

I have a problem in ha-google-home that it tries fetching alarms and timers from chromecast devices, where those don't even exist. Those can be simply fixed if we know the hardware model of the devices and only create timer/alarm sensors for devices that are supported like "Google Home", "Google Home Mini" etc

Expose hardware name in the Device

---

example/get_tokens.py
glocaltokens/client.py
glocaltokens/scanner.py
glocaltokens/utils/logs.py
tests/test_client.py
tests/test_scanner.py
tests/test_utils.py

Maybe too redundant, but added everything just in case it is useful. Take a look at it.
Closes #47.

Added more debugging for bug-fixing

---

pyproject.toml

To make the package [PEP-561](https://www.python.org/dev/peps/pep-0561/) compliant this PR 
enables distributing typing info
Required by: https://github.com/leikoilja/ha-google-home/pull/88

Enable distributing type info with a package

---

glocaltokens/client.py
glocaltokens/const.py
glocaltokens/scanner.py
poetry.lock
pyproject.toml

I noticed in my logs and logs of other people that zeroconf discovery is actually pretty fast and all devices are discovered under 1 second.
Reducing this timeout will make `google_home` initial setup and component startup much faster.
Also add an option to `get_google_devices` to override it.
For some reason `pylint` was broken because it was unable to find `socket` symbols which are implemented in C. Fixed that as well.
And `decorator==5.0.1` no longer exists: https://pypi.org/project/decorator/#history

Reduce discovery timeout

---

.github/dependabot.yml
.github/labeler.yml

As we discussed, set versioning stratagy to lockfile only to prevent changed in `pyproject.toml` and preserve library versioning constraints. This should prevent `grpcio` updates. Also as a library `glocaltokens` should have more relaxed versioning requirements.
Also import updated Labeler config from `ha-google-home`.

Set Dependabot versioning strategy

---

.pre-commit-config.yaml
glocaltokens/client.py
glocaltokens/scanner.py
glocaltokens/utils/types.py
pyproject.toml
setup.cfg
tests/assertions.py
tests/test_client.py
tests/test_scanner.py

Mypy helps to catch places where `Optional` is not handled properly.
Fixes #66

Add more type hints, fix some pylint warnings

---

.github/dependabot.yml

These are useless. `dependencies` is the default anyway.

Cleanup depdendabot config

---

glocaltokens/client.py
glocaltokens/const.py
setup.cfg
tests/assertions.py
tests/factory/providers.py
tests/test_client.py
tests/test_scanner.py
tests/test_utils.py

Enforce the same strict checks as we do in `ha-google-home`.

Add type hints to tests, enable strict checks

---

pyproject.toml
setup.cfg

I tested that it works fine in HA, including login flow.
Please create a release and publish the new version after merging 🙂
Btw, I can try to configure poetry to detect version from github release so these version bumps won't be needed. We can even automate publishing to pypi after that. So just creating a github release should do all the work. Do you want to try that? 🙂

Release 0.3.1

---

.github/workflows/publish.yml
pyproject.toml

This action is supposed to automatically assign version based on git tag, build package and publish it on PyPI.
Haven't tested everything together, especially the last command.
Locally this will build version `0.0.0` but this should be fine because with this we only need to publish it with this action.
Poetry just merged support of plugins which will be released in v1.2. After that we can use this as a real plugin, right now it's not very simple to install: https://github.com/mtkennerly/poetry-dynamic-versioning
Closes #88

Action to automatically publish new version on PyPI

---

poetry.lock
pyproject.toml

This was added by dependabot in https://github.com/leikoilja/glocaltokens/pull/60 with no particular reason.
HA Core uses the latest 0.36.2:
https://github.com/home-assistant/core/blob/70338da50efd6f5537fb8463ac42450bf7010e19/homeassistant/package_constraints.txt#L37
Tested locally that it still works.

Unconstrain zeroconf version

---

glocaltokens/client.py
glocaltokens/const.py
glocaltokens/scanner.py
glocaltokens/types.py
tests/test_client.py
tests/test_scanner.py

- Rename `google_device` to `network_device`.
- Remove `ip_address` and `port` fields from `Device` constructor, they're only used in tests and add code complexity.
- Stop discovery after the timeout. Inspired by pychromecast. Otherwise it can modify list of discovered devices while it's being processed. Also it spams logs.
- Store devices in dict to filter duplicates. Before `update_service` was inserting copies in devices list.
- Handle remove `remove_service`.
- Replace `GoogleDevice` class with `NetworkDevice` named tuple. It should really just hold the data, all checks are moved outside.
- Remove unnecessary type hints from `Final`, they can be inferred automatically.
- Remove few tests which are no longer needed.
- Update some comments.
Tested locally on my HA instance.

Refactor scanner

---

glocaltokens/client.py
glocaltokens/const.py
glocaltokens/scanner.py

Finally use these new IDs.
I have a speaker stereo pair which shows in the app (and in home graph) as a single virtual device with model `Google Cast Group`.
But when the main speaker in this pair is not reachable (due of https://github.com/leikoilja/ha-google-home/issues/202), it starts to appear as name of that speaker instead of name of the pair.
This leads to non consistent results from glocaltokens.
Local auth tokens are actually per physical device, so glocaltokens should ignore any virtual groups and return only list of actual devices.
This unique id is the same for speaker pair device in home graph and actual device, so in both cases it'll be matched to corresponding network device. Use the name of that network device for consistency.

Match devices by unique ID

---

glocaltokens/client.py
glocaltokens/const.py
glocaltokens/scanner.py
tests/factory/providers.py
tests/test_client.py

This changes `disable_discovery` from a bool to `address_list` containing a dict. Example dict: ``{"Living room": "192.168.0.69"}` Not setting the address_list results in discovery been enabled. Setting it to and empty dict results in discovery being disabled.
I was not 100% sure on how to best implement this, so please provide feedback if something can be done better. 😄 
Code is tested, but can someone double check to make sure that we are not breaking anything with this.

Add possibility of using an address list instead

---

.github/workflows/build.yml
poetry.lock
pyproject.toml

Bump grpcio==1.43.0 which is the latest version that Home Assistant also supports:
https://github.com/home-assistant/core/blob/9ce2e9e8f4e9afaefc4a66e788d503ebe817c327/homeassistant/package_constraints.txt

Bump grpcio==1.43.0

---

poetry.lock
pyproject.toml

I tested locally that with grpcio-tools uninstalled, the integration still works.

Move grpcio-tools to dev dependencies

---

poetry.lock
pyproject.toml

With some Frenk's [help](https://github.com/home-assistant/wheels-custom-integrations/issues/590#issuecomment-1049845684):
What we had:
```
[tool.poetry.dependencies]
python = "^3.8"
gpsoauth = "^1.0.0"
requests = "^2.25.1"
simplejson = "^3.17.2"
zeroconf = "^0.36.2"
grpcio = "1.43.0"
```
Those are pretty hard pins for a library.
requests is limited from =>2.25.1 and <2.26.0, while Home Assistant requires [2.27.1](https://github.com/home-assistant/core/blob/dev/requirements.txt#L21)
Zeroconf has similar issues: https://github.com/home-assistant/core/blob/dev/requirements_all.txt#L2536
grpcio is hard pinned, which a library should never do. Home Assistant side: https://github.com/home-assistant/core/blob/dev/homeassistant/package_constraints.txt#L48-L51
So, on the first quick pass, those …

Resolving HomeAssistant dependency conflicts

---

poetry.lock
pyproject.toml

Bumping gpsoauth version to the latest, fixing the outstanding issue we have #245 .
Closes #245 
Testes locally to work just fine :) 
Let's merge it in and release `glocaltokens` new minor version

Bump gpsoauth to v1.0.1

---

glocaltokens/client.py
tests/test_client.py

Apparently I was able to create Google account (not email) which has `+` in the username. And to get master token for it, `+` should be replaced with `%2B`.
Fixes #260

Escape plus sign in the username

---

poetry.lock
pyproject.toml

This should allow minor versions to be updated on HA side without changed in glocaltokens.

Relax requirements for deps which are pinned in HA

---

.github/actions/setup-environment/action.yml
.github/workflows/build.yml
.github/workflows/linting-and-testing.yaml
.github/workflows/publish.yml

* Cache pip use base to not reinstall poetry on every job.
* Fix for macos which was using python from runner instead of provided.

Cache poetry itself

---

.pre-commit-config.yaml
glocaltokens/client.py
glocaltokens/const.py
glocaltokens/scanner.py
glocaltokens/types.py
glocaltokens/utils/logs.py
glocaltokens/utils/network.py
glocaltokens/utils/token.py
pyproject.toml
tests/assertions.py
tests/factory/providers.py
tests/test_client.py
tests/test_scanner.py
tests/test_utils.py
uv.lock

Another great Rust tool from Astral. It's many times faster than black and in some cases it formats code better.

Replace black with ruff format

---

pyproject.toml

I read [PEP 621](https://peps.python.org/pep-0621/) and some fields are now different and some left from Poetry and not used.

Update pyproject.toml according to PEP621

---

.github/dependabot.yml
pyproject.toml

Dependabot doesn't work well with dynamic version: https://github.com/dependabot/dependabot-core/issues/12340
This should help for build to pass, at least further.

Add fallback version for dependabot build
